// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcbhucIwh7bPZ01dGvDHEoxIIzbsB3GKA',
    appId: '1:190038800057:web:32fa43069ac51fd5570d68',
    messagingSenderId: '190038800057',
    projectId: 'pkw40304',
    authDomain: 'pkw40304.firebaseapp.com',
    storageBucket: 'pkw40304.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWvtO-RO8AKaLaAFFzL2wOAZRvz3vF8DE',
    appId: '1:190038800057:android:70bf20d303bfea3a570d68',
    messagingSenderId: '190038800057',
    projectId: 'pkw40304',
    storageBucket: 'pkw40304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3nVEJnmQv96KnXPBIQxvBKmAo6OCRP_U',
    appId: '1:190038800057:ios:bc907f7fb271f8c5570d68',
    messagingSenderId: '190038800057',
    projectId: 'pkw40304',
    storageBucket: 'pkw40304.appspot.com',
    iosClientId: '190038800057-h4lc1e3ln952fjqr95sepm9a3p6g02ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.patient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3nVEJnmQv96KnXPBIQxvBKmAo6OCRP_U',
    appId: '1:190038800057:ios:bc907f7fb271f8c5570d68',
    messagingSenderId: '190038800057',
    projectId: 'pkw40304',
    storageBucket: 'pkw40304.appspot.com',
    iosClientId: '190038800057-h4lc1e3ln952fjqr95sepm9a3p6g02ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.patient',
  );
}
